name = "cf-note"
main = "src/index.js"
compatibility_date = "2026-01-15"

[[rules]]
type = "Data"
globs = ["**/*.ico"]
fallthrough = false

[[d1_databases]]
binding = "DB"
database_name = "cf-note-db"
database_id = "a4745e99-ad70-4179-889b-894e2aa812ed"
