name = "cf-note"
main = "src/index.js"
compatibility_date = "2026-01-15"

[[rules]]
type = "Data"
globs = ["**/*.ico"]
fallthrough = false

[[d1_databases]]
binding = "DB"
database_name = "cf-note-db"
database_id = "99c13bea-c0de-4943-97c8-553e14de4032"
